language: node_js
node_js:
- '10'
before_install:
- npm install -g npm@^6.13.0
script:
- npm run build
deploy:
  provider: npm
  edge: true
  email: brettswift@gmail.com
  api_key:
    secure: KHLIjIZ24T4B13GO1RR9yQk6OgOA/zXhilmlGf6vcoh3oTQDChsIJX/9PLXWIC6S1KkmkfF7qx3T+Rbfd5lVULvnZaB3lFjbkBWJEqNW4MddHztODB+z/qoKNFsLKQn30OfL1C2z7d4m3Xrj+sgiKPlikmUhj26Yzh+MohEtUZgHAjtrtchcMST9pvNWkWqqpgA2tJex930TYlt870ryZiEZGIQlyY/wCYfosZ164nFrcEHMpp7gq66wP4jE/9oMSgEVBqf6pBG2Gyk2Ysm3EDqu1IlEntsANKa6UxIOdp686mub6v2fPEfYr00b+/a+jAzOwjv/qRcfvpJF0cGkG3htYsNMCiveNX39Jz1RkQDdBwWtCarHKArnCZas22L/w5EVfLAU5fBZiqDYIoR/Cs8oCF4xSO+po6yI4MargcAaokbdmu5hyvrycafb7ddwN3KH54W/cvmdkOPhxAgeJkMjYfNpclnIW74BlIw7aqnfFoge4emhJU5rZEIZTght6Xm26pOoFw8mZ7TyMxlVB/AJ8yW57cE9o3dvd6rjSPgh5kZyAP8M0Gt7rHrQh5Yo3Je4VzNF7f7rgsdghCQ0CtM3Py+ROhXZP5fYKWwCk7dCqLG1K4AppOzwAezH2JuQRYTg7k3R4QaqRcUcesa2xaHKs0C3ofrYB7/gCBg2fxo=
  on:
    tags: true
    repo: brettswift/cdk-git-config
