language: node_js
node_js:
- '10'
before_install:
- npm install -g npm@^6.13.0
script:
- npm run build
deploy:
  provider: npm
  edge: true
  email: brettswift@gmail.com
  api_key: "$NPM_TOKEN"
  on:
    tags: true
